---
- name: Deploy configuration file
  template:
    src: config.json.j2
    dest: "{{ hound_data_folder }}/config.json"
    owner: "{{ hound_user }}"
    group: "{{ hound_user }}"
    mode: 0644
  notify:
    - restart hound
...