---
- name: Create hound user
  user:
    name: "{{ hound_user }}"
    state: present

- name: Install hound and houndd using go command line
  shell: "/usr/local/go/bin/go get {{ hound_go_url }}"
  become: yes
  become_user: "{{ hound_user }}"
  register: hound_install
  changed_when: "'(download)' in hound_install.stdout"

- name: Install systemd service
  template:
    src: hound.service.j2
    dest: /etc/systemd/system/hound.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon-reload
    - restart hound
...
